// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6a9ff097-c13e-4c1c-b48d-19f393269f3f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fdL3E23BU",
    "aws_user_pools_web_client_id": "48lftdpg1bj2juvnv5rq77grmc",
    "aws_user_files_s3_bucket": "angular5samplebucket",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "ScheduleAppointment",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
